#!/bin/sh
### BEGIN INIT INFO
# Provides:          ld382a.py
# Required-Start:    $remote_fs $network
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# X-Interactive:
# Description: LED-Controller-Server for LD382A
# Short-Description:    LCS for LD382A
### END INIT INFO

PATH='/sbin:/bin:/usr/bin:/usr/local/bin'

NAME=lcs
LCS=/usr/local/bin/ld382a.py
IP=192.168.188.244
FIND_PID="ps -eo pid,args | grep ld382a.py | grep $IP | awk '{print \$1}'"

RET=0

. /lib/lsb/init-functions

kill_pid () {
    PID=$(eval $FIND_PID)
    if [ ! -z $PID ]; then
        kill $PID
        PID=$(eval $FIND_PID)
        if [ ! -z $PID ]; then
            sleep 3
            kill -9 $PID
        fi
    fi
}

case "$1" in
    start|restart)
    	kill_pid
	log_daemon_msg "Starting LED-Controller-Server\n"
	echo
    	$LCS -C $IP 2>&1 &
        ;;
    stop)
	log_daemon_msg "Stopping LED-Controller-Server\n"
    	kill_pid 2>&1 &
        ;;
    *)
    	log_failure_msg "Usage: /etc/init.d/$NAME {start|stop|restart}"
        ;;
esac

exit 0
